[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 5001
address = "0.0.0.0"

[theme]
primaryColor="#10A37F"  
backgroundColor="#202123"  
secondaryBackgroundColor="#2B2D31"  
textColor="#E0E0E0" 
font="monospace"
